name: AutoCodeRover
on:
  workflow_call:
    inputs:
      filename:
        description: 'A filename to the issue description'
        required: true
        type: string
jobs:
  get_issue:
    name: Load Issue
    runs-on: ubuntu-latest
    steps:
      - name: Download Issue Description
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.filename }}
      - shell: bash
        run: |
          value=`cat ${{ inputs.filename }}`
          echo The result is $value

