name: AutoCodeRover
on:
  workflow_call:
    inputs:
      artifact:
        description: 'artifact name to download'
        required: true
        type: string
      filename:
        description: 'filename to the issue description'
        required: true
        type: string
jobs:
  get_issue:
    name: Load Issue
    runs-on: ubuntu-latest
    steps:
      - name: Download Issue Description
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact }}
      - shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACR_TOKEN: ${{ secrets.ACR_TOKEN }}
          ACR_HOST: ${{ secrets.ACR_HOST }}
          DESCRIPTION: "test.c: In function ‘bad’: test.c:15:1: error: expected expression before ‘}’"


        run: |
          description=`cat ${{ inputs.filename }}`
          echo The result is $description
          echo The Host is $ACR_HOST
          curl --header "acr-auth-token: $ACR_TOKEN" --insecure -d '{"agent" : "GitHub Action", "repository_url": "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}", "language": "c", "description": `cat ${{ inputs.filename }}`, "type": "bug fix" , "branch": "${{ github.ref_name }}", "commit": "${{ github.ref_name }}" }' -X POST "$ACR_HOST/ci/github/run"